### ISSUE TITLE
crash on multiplayer server startup

### ISSUE THREAD

**Issue by szentigrad3** [Nexela/PickerCheats#2]
------------- Error -------------
Error while running setup for entity prototype "picker-cheats-super-loader" (loader): Entity must produce no item result result or mine to an item that isn't hidden when next_upgrade is set.
Modifications: Picker Cheats
---------------------------------

**Comment by Nexela** [comment]
Please post your factorio-current.log in future reports. This should be fixed, but since I don't have any log I didn't feel like testing it.
